#include "file_system.h"

const char *DEFAULT_HTML_CONTENT = "<!DOCTYPE html>\n"
"<html lang='en'>\n"
"<head>\n"
"    <meta charset='UTF-8'>\n"
"    <meta name='viewport' content='width=device-width, initial-scale=1.0'>\n"
"    <title>ESP32-C5 Honeypot Configuration</title>\n"
"    <style>\n"
"        body { font-family: Arial, sans-serif; margin: 0; padding: 20px; }\n"
"        .container { max-width: 600px; margin: 0 auto; }\n"
"        .form-group { margin-bottom: 15px; }\n"
"        label { display: block; margin-bottom: 5px; }\n"
"        input[type='text'], input[type='password'] { width: 100%; padding: 8px; }\n"
"        button { background: #007bff; color: white; padding: 10px 20px; border: none; cursor: pointer; }\n"
"        button:hover { background: #0056b3; }\n"
"        .webhook-info { font-size: 12px; margin-top: 5px; color: #666; }\n"
"        code { background: #f5f5f5; padding: 2px 4px; border-radius: 3px; }\n"
"        pre { background: #f5f5f5; padding: 10px; border-radius: 3px; overflow-x: auto; font-size: 12px; }\n"
"    </style>\n"
"</head>\n"
"<body>\n"
"    <div class='container'>\n"
"        <h1>ESP32-C5 Honeypot Configuration</h1>\n"
"        <form id='configForm'>\n"
"            <div class='form-group'>\n"
"                <label for='ssid'>WiFi SSID:</label>\n"
"                <input type='text' id='ssid' name='ssid' required>\n"
"            </div>\n"
"            <div class='form-group'>\n"
"                <label for='password'>WiFi Password:</label>\n"
"                <input type='password' id='password' name='password' required>\n"
"            </div>\n"
"            <div class='form-group'>\n"
"                <label for='webhook'>Webhook URL:</label>\n"
"                <input type='text' id='webhook' name='webhook'>\n"
"                <div class='webhook-info'>\n"
"                    <p><strong>Note:</strong> HTTPS webhooks (like Discord) are not directly supported due to ESP32 SSL limitations.</p>\n"
"                    <p>For Discord notifications, set up a Raspberry Pi relay:</p>\n"
"                    <ol>\n"
"                        <li>Install required packages on your Raspberry Pi:</li>\n"
"                        <pre>sudo apt update\nsudo apt install -y python3-pip\npip3 install flask requests</pre>\n"
"                        <li>Create a file named <code>webhook_relay.py</code> with the following content:</li>\n"
"                        <pre>from flask import Flask, request, jsonify\nimport requests\nimport logging\n\napp = Flask(__name__)\n\n# Configure logging\nlogging.basicConfig(\n    level=logging.INFO,\n    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',\n    handlers=[logging.FileHandler(\"webhook_relay.log\"), logging.StreamHandler()]\n)\nlogger = logging.getLogger(__name__)\n\n# Your Discord webhook URL\nDISCORD_WEBHOOK_URL = \"https://discord.com/api/webhooks/your_webhook_id/your_webhook_token\"\n\n@app.route('/webhook', methods=['POST'])\ndef relay_webhook():\n    try:\n        data = request.json\n        logger.info(f\"Received webhook: {data}\")\n        \n        # Forward the payload to Discord\n        response = requests.post(DISCORD_WEBHOOK_URL, json=data)\n        \n        if response.status_code == 204 or response.status_code == 200:\n            logger.info(\"Successfully forwarded to Discord\")\n            return jsonify({\"status\": \"success\"}), 200\n        else:\n            logger.error(f\"Failed to forward: {response.status_code} - {response.text}\")\n            return jsonify({\"status\": \"error\", \"details\": response.text}), 500\n            \n    except Exception as e:\n        logger.error(f\"Error processing webhook: {str(e)}\")\n        return jsonify({\"status\": \"error\", \"details\": str(e)}), 500\n\nif __name__ == '__main__':\n    logger.info(\"Webhook relay starting...\")\n    # Run on all interfaces, port 8080\n    app.run(host='0.0.0.0', port=8080)</pre>\n"
"                        <li>Replace <code>DISCORD_WEBHOOK_URL</code> with your actual Discord webhook URL</li>\n"
"                        <li>Run the script: <code>python3 webhook_relay.py</code></li>\n"
"                        <li>To make it start automatically on boot, create a systemd service:</li>\n"
"                        <pre>sudo nano /etc/systemd/system/webhook-relay.service</pre>\n"
"                        <li>Add this content:</li>\n"
"                        <pre>[Unit]\nDescription=Webhook Relay Service\nAfter=network.target\n\n[Service]\nUser=pi\nWorkingDirectory=/home/pi\nExecStart=/usr/bin/python3 /home/pi/webhook_relay.py\nRestart=always\nRestartSec=5\n\n[Install]\nWantedBy=multi-user.target</pre>\n"
"                        <li>Enable and start the service:</li>\n"
"                        <pre>sudo systemctl enable webhook-relay\nsudo systemctl start webhook-relay</pre>\n"
"                        <li>Enter the webhook URL here in the format: <code>http://YOUR_PI_IP:8080/webhook</code></li>\n"
"                    </ol>\n"
"                    <p>The relay will accept HTTP requests from the ESP32 and forward them to Discord using proper HTTPS.</p>\n"
"                </div>\n"
"            </div>\n"
"            <button type='submit'>Save Configuration</button>\n"
"        </form>\n"
"    </div>\n"
"    <script>\n"
"        document.getElementById('configForm').onsubmit = function(e) {\n"
"            e.preventDefault();\n"
"            const data = {\n"
"                ssid: document.getElementById('ssid').value,\n"
"                password: document.getElementById('password').value,\n"
"                webhook: document.getElementById('webhook').value\n"
"            };\n"
"            fetch('/api/config', {\n"
"                method: 'POST',\n"
"                headers: { 'Content-Type': 'application/json' },\n"
"                body: JSON.stringify(data)\n"
"            })\n"
"            .then(response => response.json())\n"
"            .then(data => {\n"
"                if (data.success) {\n"
"                    alert('Configuration saved successfully!');\n"
"                } else {\n"
"                    alert('Error saving configuration');\n"
"                }\n"
"            })\n"
"            .catch(error => {\n"
"                console.error('Error:', error);\n"
"                alert('Error saving configuration');\n"
"            });\n"
"        };\n"
"    </script>\n"
"</body>\n"
"</html>"; 