#include "file_system.h"

const char *DEFAULT_HTML_CONTENT = "<!DOCTYPE html>\n"
"<html lang='en'>\n"
"<head>\n"
"    <meta charset='UTF-8'>\n"
"    <meta name='viewport' content='width=device-width, initial-scale=1.0'>\n"
"    <title>ESP32-C5 Honeypot Configuration</title>\n"
"    <style>\n"
"        body { font-family: Arial, sans-serif; margin: 0; padding: 20px; }\n"
"        .container { max-width: 600px; margin: 0 auto; }\n"
"        .form-group { margin-bottom: 15px; }\n"
"        label { display: block; margin-bottom: 5px; }\n"
"        input[type='text'], input[type='password'] { width: 100%; padding: 8px; }\n"
"        button { background: #007bff; color: white; padding: 10px 20px; border: none; cursor: pointer; }\n"
"        button:hover { background: #0056b3; }\n"
"        .webhook-info { font-size: 12px; margin-top: 5px; color: #666; }\n"
"        code { background: #f5f5f5; padding: 2px 4px; border-radius: 3px; }\n"
"        pre { background: #f5f5f5; padding: 10px; border-radius: 3px; overflow-x: auto; font-size: 12px; }\n"
"    </style>\n"
"</head>\n"
"<body>\n"
"    <div class='container'>\n"
"        <h1>ESP32-C5 Honeypot Configuration</h1>\n"
"        <form id='configForm'>\n"
"            <div class='form-group'>\n"
"                <label for='ssid'>WiFi SSID:</label>\n"
"                <input type='text' id='ssid' name='ssid' required>\n"
"            </div>\n"
"            <div class='form-group'>\n"
"                <label for='password'>WiFi Password:</label>\n"
"                <input type='password' id='password' name='password' required>\n"
"            </div>\n"
"            <div class='form-group'>\n"
"                <label for='webhook'>Webhook URL:</label>\n"
"                <input type='text' id='webhook' name='webhook'>\n"
"                <div class='webhook-info'>\n"
"                    <p><strong>Note:</strong> HTTPS webhooks (like Discord) are not directly supported due to ESP32 SSL limitations.</p>\n"
"                    <p>For webhook notifications, use webhook.site:</p>\n"
"                    <ol>\n"
"                        <li>Go to <a href='https://webhook.site' target='_blank'>webhook.site</a></li>\n"
"                        <li>Copy the unique URL provided (should start with http://)</li>\n"
"                        <li>Paste this URL in the webhook field above</li>\n"
"                        <li>Keep the webhook.site page open to see incoming alerts in real-time</li>\n"
"                    </ol>\n"
"                    <p>webhook.site supports HTTP without redirects, making it compatible with ESP32's HTTP client.</p>\n"
"                </div>\n"
"            </div>\n"
"            <button type='submit'>Save Configuration</button>\n"
"        </form>\n"
"    </div>\n"
"    <script>\n"
"        document.getElementById('configForm').onsubmit = function(e) {\n"
"            e.preventDefault();\n"
"            const data = {\n"
"                ssid: document.getElementById('ssid').value,\n"
"                password: document.getElementById('password').value,\n"
"                webhook: document.getElementById('webhook').value\n"
"            };\n"
"            fetch('/api/config', {\n"
"                method: 'POST',\n"
"                headers: { 'Content-Type': 'application/json' },\n"
"                body: JSON.stringify(data)\n"
"            })\n"
"            .then(response => response.json())\n"
"            .then(data => {\n"
"                if (data.success) {\n"
"                    alert('Configuration saved successfully!');\n"
"                } else {\n"
"                    alert('Error saving configuration');\n"
"                }\n"
"            })\n"
"            .catch(error => {\n"
"                console.error('Error:', error);\n"
"                alert('Error saving configuration');\n"
"            });\n"
"        };\n"
"    </script>\n"
"</body>\n"
"</html>"; 